### ISSUE TITLE
Cannot sequence jobs using artifactory resource

### ISSUE THREAD

**Issue by labrown** [orange-cloudfoundry/artifactory-resource#5]
I'm trying to build a pipeline using where the first job builds a binary and does a 'put' task to upload it to Artifactory using this resource.  Then the second job triggers on that put, retrieves the binary and tests it.

It appears that the 'out' command is not returning any version information in its output so there is no version data available for the next job to use to retrieve the desired version of the binary.

This is all at work so I don't have the source code handy to include in this issue report.  I'll see about setting up an environment at home and testing it locally to provide more details.

**Comment by ArthurHlt** [comment]
I need more context for this one like your pipeline but for downloading afterward you need to use the in part.

Out and in are not linked in concourse, you might take a look at https://concourse-ci.org/implementing-resource-types.html#resource-in to maybe have a better understanding about concourse

**Comment by labrown** [comment]
Thanks. I'm aware how resources work. :-)

Here is a mostly complete example pipeline.  but should explain the issue.

`resource_types:
- name: artifactory
  type: docker-image
  source:
    repository: orangeopensource/artifactory-resource

resources:
- name: test-artifactory
  type: artifactory
  source:
    url: ((artifactory_endpoint))
    user: ((artifactory_username))
    password: ((artifactory_password))
    ca_cert: ((ca_certificates))
    log_level: DEBUG
    regexp: false
    version: "1.x.x"
    pattern: ((artifactory_repository))/testing/testing-(*)

jobs:
- name: generate-file
  serial: true
  plan:
  - in_parallel:
    - get: s3-container-image
      params:
        unpack: true
      tags:
      - ((worker_tags))
  ##
  ## Generate a file to put into artifactory
  ##
  - task: generate-file
    config:
      platform: linux
      outputs:
      - name: test-file
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          set -x
          date > test-file/testing-1.0.0
          echo >> test-file/testing-1.0.0
          /bin/ls -l /usr/bin >> test-file/testing-1.0.0
          echo
          echo testing-1.0.0 is:
          cat test-file/testing-1.0.0
  ##
  ## Send build artifact to artifactory
  ##
  - put: test-artifactory
    params:
      source: test-file/testing-*
      target: ((artifactory_repository))/testing/

##
## Get version of file we just put into artifactory and use it
- name: retrieve-file
  plan:
  - in_parallel:
    - get: test-artifactory
      passed:
      - generate-file
      trigger: true
    - get: s3-container-image
      params:
        unpack: true
  ##
  ## Use retrieved file
  ##
  - task: test2
    config:
      platform: linux
      inputs:
      - name: test-artifactory
      run:
        path: bash
        args:
        - -c
        - |
          set -eu
          set -x
          echo
          echo testing-1.0.0 is:
          cat test-artifactory/testing-1.0.0
`
